#workspace:
#  base: /go
#  path: src/github.com/zhanghudong/drone-test
#
#pipeline:
#  testing:
#    image: golang:latest
#    commands:
#      - go env
#      - go version
#      - go build
#  publish:
#    image: plugins/docker
#    repo: zhanghudong/drone-test
#    dockerfile: Dockerfile
#    tags: latest
#    pull: true
#    registry: https://cloud.docker.com
#    group: release
#    auto_tag: true
#    when:
#      event: [ push, tag ]
#      local: false


kind: pipeline
name: default

steps:
  - name: test
    image: golang
    commands:
      - go test
      - go build
  - name: docker
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker ps -a

  volumes:
    - name: dockersock
      host:
        path: /var/run/docker.sock