workspace:
  base: /go
  path: src/github.com/zhanghudong/drone-test

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  testing:
    image: golang:1.10.0
    commands:
      - go test -v .
      - go vet
  publish:
    image: plugins/docker
    repo: zhanghudong/drone-test
    dockerfile: Dockerfile
    tags: latest
    pull: true
    registry: https://cloud.docker.com
    group: release
    auto_tag: true
    when:
      event: [ push, tag ]
      local: false


