#workspace:
#  base: /go
#  path: src/github.com/zhanghudong/drone-test
#
pipeline:
  build:
    image: golang:latest
    commands:
      - go build
      - go test
#  publish_latest:
#    image: plugins/docker
#    repo: zhanghudong/drone-test
#    secrets: [ docker_username, docker_password ]
#    auto_tag: truels
#    dockerfile: Dockerfile
#    when:
#      event: [push,tag]

#    auto_tag: true
#    when:
#      event: deployment
#      environment: staging 啊大大好看的

#  publish_to_prod:
#    image: plugins/docker
#    registry: cloud.docker.com
#    repo: cloud.docker.com/repository/docker/zhanghudong/drone-test
#    when:
#      event: deployment
#      environment: production

#kind: pipeline
#name: default
#
#workspace:
#  base: /go
#  path: src/github.com/zhanghudong/drone-test
#
#steps:
#  - name: test
#    image: golang
#    volumes:
#      - name: deps
#        path: /go
#    commands:
#      - go test
#  - name: build
#    image: golang
#    volumes:
#      - name: deps
#        path: /go
#    commands:
#      - go build
#
#  - name: dockerr
#    image: plugins/docker
#    repo: zhanghudong/drone-test
#    dockerfile: Dockerfile

#官方
#pipeline:
#  backend:
#    image: golang
#    commands:
#      - go build
#      - go test
#
#  publish:
#    image: plugins/docker
#    repo: zhanghudong/drone-test
#    tags: [ 1, 1.1, latest ]
#    registry: https://cloud.docker.com/u/zh1376639963/repository/docker/zh1376639963/nxns

#  notify:
#    image: plugins/slack
#    channel: developers
#    username: drone
